kind: PersistentVolume
apiVersion: v1
metadata:
  name: filenet-filestore-pv
spec:
  capacity:
    storage: 100Gi
  nfs:
    server: xxxxxxxxxx
    path: >-
      /data/FileNet/filenet-filestore
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-nfs-storage
  mountOptions:
    - nfsvers=4
    - nolock
  volumeMode: Filesystem
